### ISSUE TITLE
Noslate思路不错， 请问如何解决资源(CPU/MEM/IO)挤况和隔离的问题

### ISSUE THREAD

**Issue by etoah** [noslate-project/noslate#42]
比如： docker通过cgroups限制cpu、mem的资源， 请问Noslate怎么做的

**Comment by mariodu** [comment]
Noslate Workers 通过 Turf 实现对 CPU、Memory 资源的隔离，目前通过采样的方式进行限制，后续会提供基于 cgroup 的隔离实现。
另外，运行时层面会对连续的执行时间限制，防止 busy loop 等。

相关的文档会陆续更新。

**Comment by zhanzekun** [comment]
这里关于隔离性的文档有更新了吗
