### ISSUE TITLE
docker: Error response from daemon: Head "https://ghcr.io/v2/noslate-project/noslate-demo/manifests/0.0.1": denied.

### ISSUE THREAD

**Issue by hyf3513OneGO** [noslate-project/noslate#50]
Unalble to pull docker image
![image](https://user-images.githubusercontent.com/67197231/200206472-5324dba6-380c-494b-89af-3d2816aff185.png)
I've tried pulling  this image on both local environment and server's environment(US)
SystemInfo:
Centos 7.6
Docker 20.10.17

I try to open this URL https://ghcr.io/v2/noslate-project/noslate-demo,It returns 404 not found

**Comment by mariodu** [comment]
fixed.
